// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StandingOut.Data;

namespace StandingOut.Data.Migrations
{
    [DbContext(typeof(DbEntities))]
    [Migration("20190318193818_systemToolsTable")]
    partial class systemToolsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("StandingOut.Data.Models.ClassSession", b =>
                {
                    b.Property<Guid>("ClassSessionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AppointmentId");

                    b.Property<int?>("ClassId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<DateTime>("EndDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("OwnerId");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("ClassSessionId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("OwnerId");

                    b.ToTable("ClassSessions");
                });

            modelBuilder.Entity("StandingOut.Data.Models.ErrorLog", b =>
                {
                    b.Property<Guid>("ErrorLogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("InnerException")
                        .HasMaxLength(2000);

                    b.Property<string>("InnerStackTrace");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("LogDate");

                    b.Property<string>("Message")
                        .HasMaxLength(2000);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Path")
                        .HasMaxLength(2000);

                    b.Property<string>("StackTrace");

                    b.HasKey("ErrorLogId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("StandingOut.Data.Models.SafeguardReport", b =>
                {
                    b.Property<Guid>("SafeguardReportId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ClassSessionId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("LogDate");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("UserId");

                    b.HasKey("SafeguardReportId");

                    b.HasIndex("ClassSessionId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UserId");

                    b.ToTable("SafeguardReports");
                });

            modelBuilder.Entity("StandingOut.Data.Models.SessionAttendee", b =>
                {
                    b.Property<Guid>("SessionAttendeeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AppointmentId");

                    b.Property<bool>("Attended");

                    b.Property<Guid>("ClassSessionId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("JoinDate");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<Guid?>("SessionGroupId");

                    b.Property<string>("UserId");

                    b.HasKey("SessionAttendeeId");

                    b.HasIndex("ClassSessionId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SessionGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("SessionAttendees");
                });

            modelBuilder.Entity("StandingOut.Data.Models.SessionGroup", b =>
                {
                    b.Property<Guid>("SessionGroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ClassSessionId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.HasKey("SessionGroupId");

                    b.HasIndex("ClassSessionId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("SessionGroups");
                });

            modelBuilder.Entity("StandingOut.Data.Models.SessionMedia", b =>
                {
                    b.Property<Guid>("SessionMediaId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ClassSessionId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<int>("Type");

                    b.HasKey("SessionMediaId");

                    b.HasIndex("ClassSessionId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("SessionMedias");
                });

            modelBuilder.Entity("StandingOut.Data.Models.SessionMessage", b =>
                {
                    b.Property<Guid>("SessionMessageId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ClassSessionId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("FromUserId");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("LogDate");

                    b.Property<string>("Message")
                        .IsRequired();

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<Guid?>("ToGroupId");

                    b.Property<string>("ToUserId");

                    b.HasKey("SessionMessageId");

                    b.HasIndex("ClassSessionId");

                    b.HasIndex("FromUserId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ToGroupId");

                    b.HasIndex("ToUserId");

                    b.ToTable("SessionMessages");
                });

            modelBuilder.Entity("StandingOut.Data.Models.Setting", b =>
                {
                    b.Property<Guid>("SettingId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AcuitySchedulingSecret")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("AcuitySchedulingUserId")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("SendGridApi")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("VidyoApplicationId")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("VidyoDeveloperKey")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("VidyoDeveloperUser")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("VidyoFfmpegDir")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("VidyoRecordingDir")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.HasKey("SettingId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("StandingOut.Data.Models.SystemTool", b =>
                {
                    b.Property<Guid>("SystemToolId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("FontAwesomeIconClass")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("NgInclude")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.HasKey("SystemToolId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("SystemTools");
                });

            modelBuilder.Entity("StandingOut.Data.Models.Tutor", b =>
                {
                    b.Property<Guid>("TutorId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CalendarId")
                        .HasMaxLength(500);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.HasKey("TutorId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Tutors");
                });

            modelBuilder.Entity("StandingOut.Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<Guid?>("TutorId");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("TutorId");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StandingOut.Data.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StandingOut.Data.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StandingOut.Data.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StandingOut.Data.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("StandingOut.Data.Models.ClassSession", b =>
                {
                    b.HasOne("StandingOut.Data.Models.User", "Owner")
                        .WithMany("ClassSessions")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("StandingOut.Data.Models.SafeguardReport", b =>
                {
                    b.HasOne("StandingOut.Data.Models.ClassSession", "ClassSession")
                        .WithMany("SafeguardReports")
                        .HasForeignKey("ClassSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StandingOut.Data.Models.User", "User")
                        .WithMany("SafeguardReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("StandingOut.Data.Models.SessionAttendee", b =>
                {
                    b.HasOne("StandingOut.Data.Models.ClassSession", "ClassSession")
                        .WithMany("SessionAttendees")
                        .HasForeignKey("ClassSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StandingOut.Data.Models.SessionGroup", "SessionGroup")
                        .WithMany("SessionAttendees")
                        .HasForeignKey("SessionGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StandingOut.Data.Models.User", "User")
                        .WithMany("SessionAttendees")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("StandingOut.Data.Models.SessionGroup", b =>
                {
                    b.HasOne("StandingOut.Data.Models.ClassSession", "ClassSession")
                        .WithMany("SessionGroups")
                        .HasForeignKey("ClassSessionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("StandingOut.Data.Models.SessionMedia", b =>
                {
                    b.HasOne("StandingOut.Data.Models.ClassSession", "ClassSession")
                        .WithMany("SessionMedia")
                        .HasForeignKey("ClassSessionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("StandingOut.Data.Models.SessionMessage", b =>
                {
                    b.HasOne("StandingOut.Data.Models.ClassSession", "ClassSession")
                        .WithMany("SessionMessages")
                        .HasForeignKey("ClassSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StandingOut.Data.Models.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StandingOut.Data.Models.SessionGroup", "ToGroup")
                        .WithMany()
                        .HasForeignKey("ToGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StandingOut.Data.Models.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("StandingOut.Data.Models.User", b =>
                {
                    b.HasOne("StandingOut.Data.Models.Tutor", "Tutor")
                        .WithMany("Users")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
